version: "3.8"
services:
  # mysql57:
  #   container_name: mysql57
  #   image: mysql/mysql-server:5.7
  #   platform: linux/amd64
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "password"
  #   ports:
  #     - "3306:3306"
  mysql80:
    container_name: mysql80
    image: mysql:8
    command:
      - "--mysql-native-password=ON"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"

  pg17:
    container_name: pg17
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"

  redis8:
    container_name: redis8
    image: redis:8
    ports:
      - "6379:6379"

  redisinsight:
    container_name: redisinsight1
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    volumes:
      - ./data/redisinsight:/db

  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"

  # dynamodb-admin:
  #   container_name: dynamodb-admin
  #   image: "aaronshaf/dynamodb-admin:latest"
  #   ports:
  #     - "8002:8002"
  #   environment:
  #     AWS_REGION: ap-southeast-2
  #     AWS_ACCESS_KEY_ID: DUMMYCOINJARKEY
  #     AWS_SECRET_ACCESS_KEY: DUMMYCOINJARSECRET
  #     DYNAMO_ENDPOINT: http://dynamodb2:8000
  #     PORT: 8002

  mongodb7:
    container_name: mongodb7
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: password

  clickhouse:
    container_name: clickhouse
    image: "clickhouse/clickhouse-server:latest"
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: "default"
      CLICKHOUSE_USER: "looi"
      CLICKHOUSE_PASSWORD: "password"
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"

  s3mock:
    container_name: s3mock
    image: "adobe/s3mock:latest"
    ports:
      - "9090:9090"
    environment:
      initialBuckets: "indices-dev"

  # s3mock-test:
  #   container_name: s3mock-test
  #   image: "adobe/s3mock:latest"
  #   expose:
  #     - "9090"
  #   environment:
  #     initialBuckets: "indices-test"

  mailcrab:
    container_name: mailcrab
    image: "marlonb/mailcrab:latest"
    ports:
      - "1080:1080"
      - "1025:1025"
