version: '3.8'
services:
  # mysql57:
  #   container_name: mysql57
  #   image: mysql/mysql-server:5.7
  #   platform: linux/amd64
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "password"
  #   ports:
  #     - "3306:3306"
  mysql80:
    container_name: mysql80
    image: mysql:8.0.32
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "127.0.0.1:3306:3306"
  pg13:
    container_name: pg13
    image: postgres:13.8
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
  redis6:
    container_name: redis6
    image: redis:6
    ports:
      - "6379:6379"
  redisinsight:
    container_name: redisinsight1
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    volumes:
      - ./data/redisinsight:/db
  dynamodb2:
    container_name: dynamodb2
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
  dynamodb-admin:
    container_name: dynamodb-admin
    image: "aaronshaf/dynamodb-admin:latest"
    ports:
      - "8002:8002"
    environment:
      AWS_REGION: ap-southeast-2
      AWS_ACCESS_KEY_ID: DUMMYCOINJARKEY
      AWS_SECRET_ACCESS_KEY: DUMMYCOINJARSECRET
      DYNAMO_ENDPOINT: http://dynamodb2:8000
      PORT: 8002

  mongodb7:
    container_name: mongodb7
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: password
